[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "ffmpeg", "git"]
aptPkgs = []

[phases.install]
cmds = ["pip3 install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["echo 'Dependencies already installed'"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_NO_MUSL = "1"
